import { CalendarDays, ChevronLeft, ChevronRight } from "lucide-react";
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { formatDateForDisplay } from "../../features/dates/date-format";

type DateInputProps = { name?: string; value?: string; defaultValue?: string; onValueChange?: (isoDate: string) => void; required?: boolean; min?: string; yearRange?: { start: number; end: number }; "aria-label"?: string; };
type PickerPanel = "calendar" | "months" | "years";
const weekdays = ["Mg", "Sn", "Sl", "Rb", "Km", "Jm", "Sb"];
const monthFormatter = new Intl.DateTimeFormat("id-ID", { month: "long", timeZone: "UTC" });

function dateFromIso(value: string) { const match = /^(\d{4})-(\d{2})-(\d{2})$/.exec(value); if (!match) return null; const date = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3]))); return date.getUTCFullYear() === Number(match[1]) && date.getUTCMonth() === Number(match[2]) - 1 && date.getUTCDate() === Number(match[3]) ? date : null; }
function toIso(date: Date) { return `${date.getUTCFullYear()}-${String(date.getUTCMonth() + 1).padStart(2, "0")}-${String(date.getUTCDate()).padStart(2, "0")}`; }
function calendarDays(viewMonth: Date) { const first = new Date(Date.UTC(viewMonth.getUTCFullYear(), viewMonth.getUTCMonth(), 1)); const start = new Date(first); start.setUTCDate(1 - first.getUTCDay()); return Array.from({ length: 42 }, (_, index) => { const date = new Date(start); date.setUTCDate(start.getUTCDate() + index); return date; }); }

export function DateInput({ name, value, defaultValue = "", onValueChange, required, min, yearRange, "aria-label": ariaLabel }: DateInputProps) {
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue); const isoValue = value ?? uncontrolledValue; const selectedDate = dateFromIso(isoValue); const nowYear = new Date().getFullYear(); const range = yearRange ?? { start: 1940, end: nowYear + 10 };
  const [open, setOpen] = useState(false); const [panel, setPanel] = useState<PickerPanel>("calendar"); const [viewMonth, setViewMonth] = useState(() => selectedDate ?? new Date()); const [position, setPosition] = useState({ top: 0, left: 16 }); const triggerRef = useRef<HTMLDivElement>(null); const popoverRef = useRef<HTMLDivElement>(null);
  useEffect(() => { if (selectedDate) setViewMonth(selectedDate); }, [isoValue]); useEffect(() => { if (!open) setPanel("calendar"); }, [open]);
  useEffect(() => { if (!open) return; const place = () => { const rect = triggerRef.current?.getBoundingClientRect(); if (!rect) return; setPosition({ top: Math.min(rect.bottom + 8, window.innerHeight - 350), left: Math.max(12, Math.min(rect.left, window.innerWidth - 316)) }); }; const outside = (event: MouseEvent) => { if (!triggerRef.current?.contains(event.target as Node) && !popoverRef.current?.contains(event.target as Node)) setOpen(false); }; place(); window.addEventListener("resize", place); window.addEventListener("scroll", place, true); document.addEventListener("mousedown", outside); return () => { window.removeEventListener("resize", place); window.removeEventListener("scroll", place, true); document.removeEventListener("mousedown", outside); }; }, [open]);
  const choose = (date: Date) => { const iso = toIso(date); setUncontrolledValue(iso); onValueChange?.(iso); setOpen(false); }; const months = Array.from({ length: 12 }, (_, month) => new Date(Date.UTC(viewMonth.getUTCFullYear(), month, 1))); const years = Array.from({ length: Math.max(0, range.end - range.start + 1) }, (_, index) => range.end - index);
  const menu = open ? createPortal(<div ref={popoverRef} className="date-picker-popover" style={{ top: position.top, left: position.left }} role="dialog" aria-label="Pilih tanggal"><div className="date-picker-popover__header"><button type="button" aria-label="Bulan sebelumnya" onClick={() => setViewMonth((month) => new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth() - 1, 1)))}><ChevronLeft /></button><div className="date-picker-popover__title"><button type="button" onClick={() => setPanel("months")}>{monthFormatter.format(viewMonth)}</button><button type="button" onClick={() => setPanel("years")}>{viewMonth.getUTCFullYear()}</button></div><button type="button" aria-label="Bulan berikutnya" onClick={() => setViewMonth((month) => new Date(Date.UTC(month.getUTCFullYear(), month.getUTCMonth() + 1, 1)))}><ChevronRight /></button></div>{panel === "calendar" && <><div className="date-picker-popover__weekdays">{weekdays.map((day) => <span key={day}>{day}</span>)}</div><div className="date-picker-popover__days">{calendarDays(viewMonth).map((date) => { const iso = toIso(date); return <button key={iso} type="button" disabled={Boolean(min && iso < min)} className={`${iso === isoValue ? "is-selected" : ""} ${date.getUTCMonth() !== viewMonth.getUTCMonth() ? "is-outside" : ""}`} onClick={() => choose(date)}>{date.getUTCDate()}</button>; })}</div></>}{panel === "months" && <div className="date-picker-popover__months">{months.map((month) => <button key={month.getUTCMonth()} type="button" className={month.getUTCMonth() === viewMonth.getUTCMonth() ? "is-selected" : ""} onClick={() => { setViewMonth(month); setPanel("calendar"); }}>{monthFormatter.format(month)}</button>)}</div>}{panel === "years" && <div className="date-picker-popover__years">{years.map((year) => <button key={year} type="button" className={year === viewMonth.getUTCFullYear() ? "is-selected" : ""} onClick={() => { setViewMonth(new Date(Date.UTC(year, viewMonth.getUTCMonth(), 1))); setPanel("calendar"); }}>{year}</button>)}</div>}</div>, document.body) : null;
  return <div ref={triggerRef} className="date-picker-control"><button type="button" className="date-picker-control__trigger" aria-label={ariaLabel ?? "Pilih tanggal"} aria-haspopup="dialog" aria-expanded={open} onClick={() => setOpen((visible) => !visible)}><span className={isoValue ? "" : "is-placeholder"}>{isoValue ? formatDateForDisplay(isoValue) : "DD/MM/YYYY"}</span><CalendarDays /></button>{name && <input type="hidden" name={name} value={isoValue} required={required} />}{menu}</div>;
}
